#ifndef ENUMS_H_
#define ENUMS_H_

typedef enum {
  THEME_ECO,
  THEME_SPORT,
  THEME_COUNT,
} theme_e;

typedef enum {
  LANGUAGE_CHINESE,
  LANGUAGE_ENGLISH,
  LANGUAGE_COUNT,
} language_e;

typedef enum { METER_MODE_DAY, METER_MODE_NIGHT, METER_MODE_AUTO } meter_mode_e;

typedef enum {
  SIGNAL_LIGHT_TURN_LEFT,
  SIGNAL_LIGHT_TURN_RIGHT,
  SIGNAL_LIGHT_AUTO_START_STOP,
  SIGNAL_LIGHT_HIGH_BEAM,
  SIGNAL_LIGHT_TIRE,
  SIGNAL_LIGHT_ABS,
  SIGNAL_LIGHT_OIL_PRESSURE,
  SIGNAL_LIGHT_ENGINE_FAULT,
  SIGNAL_LIGHT_WIFI,
  SIGNAL_LIGHT_BT_ICON,
  SIGNAL_LIGHT_BT_PAIR,
  SIGNAL_LIGHT_VOLTAGE,
  SIGNAL_LIGHT_COUNT,
} signal_light_e;

typedef enum {
  LABEL_COLOR_WHITE,
  LABEL_COLOR_BLACK,
  LABEL_COLOR_RED,
  LABEL_COLOR_GREEN,
  LABEL_COLOR_BLUE,
  LABEL_COLOR_LIME_GREEN,
  LABEL_COLOR_COUNT
} label_color_e;

typedef enum {
  LABEL_FONT_PLAGIATA_27,
  LABEL_FONT_PLAGIATA_37,
  LABEL_FONT_SOURCEHANSANSCN_18,
  LABEL_FONT_SOURCEHANSANSCN_22,
  LABEL_FONT_SOURCEHANSANSCN_28,
  LABEL_FONT_SOURCEHANSANSCN_34,
  LABEL_FONT_MICROSOFT_YAHEI_18,
  LABEL_FONT_MICROSOFT_YAHEI_20,
  LABEL_FONT_MICROSOFT_YAHEI_22,
  LABEL_FONT_MICROSOFT_YAHEI_30,
  LABEL_FONT_HARMONYOS_16,
  LABEL_FONT_HARMONYOS_20,
  LABEL_FONT_HARMONYOS_24,
  LABEL_FONT_HARMONYOS_28,
  LABEL_FONT_HARMONYOS_40,
  LABEL_FONT_HARMONYOS_80,
  LABEL_FONT_HARMONYOS_MEDIUM_30,
  LABEL_FONT_COUNT
} label_font_e;

typedef enum {
  VALUE_TYPE_CHAR,
  VALUE_TYPE_FLOAT,
  VALUE_TYPE_INT,
} value_type_e;

typedef enum {
  CLICK_SHORT_UP,
  CLICK_SHORT_DOWN,
  CLICK_SHORT_BACK,
  CLICK_SHORT_SET,
  CLICK_LONG_SET,
  CLICK_LONG_BACK,
  CLICK_END,
} click_e;

typedef enum {
  PAGE_VEHICLE_SETTINGS,
  PAGE_PHONE,
  PAGE_MUSIC,
  PAGE_NAVIGATION,
  PAGE_SETTINGS,
  PAGE_COUNT,
} page_e;

typedef enum {
  WINDOW_MAIN,
  WINDOW_MENU,
  WINDOW_MOBILE,
  WINDOW_NULL,
} window_e;

#endif  // ENUMS_H_
