#ifndef ENUMS_H_
#define ENUMS_H_

typedef enum {
  SIGNAL_LIGHT_TURN_LEFT,
  SIGNAL_LIGHT_TURN_RIGHT,
  SIGNAL_LIGHT_AUTO_START_STOP,
  SIGNAL_LIGHT_HIGH_BEAM,
  SIGNAL_LIGHT_TIRE,
  SIGNAL_LIGHT_ABS,
  SIGNAL_LIGHT_OIL_PRESSURE,
  SIGNAL_LIGHT_ENGINE_FAULT,
  SIGNAL_LIGHT_WIFI,
  SIGNAL_LIGHT_BT_ICON,
  SIGNAL_LIGHT_BT_PAIR,
  SIGNAL_LIGHT_VOLTAGE,
  SIGNAL_LIGHT_COUNT,
} signal_light_e;

#endif  // ENUMS_H_